### ISSUE TITLE
Tinydetector works with this module?

### ISSUE THREAD

**Issue by luiza-avelino** [kamiazya/ngx-face-api-js#140]
This module works with the face recognition api? I mean , open the webcam and recognise the face equals the face-api project.

**Comment by kamiazya** [comment]
@luiza-avelino 

Yes.

I created a sample that uses Webcam.

Is this helpful for you?

- GitHub: https://github.com/kamiazya/ngx-face-api-js-demo-webcam
- StackBlitz(Demo App): https://ngx-face-api-js-demo-webcam.stackblitz.io/
- StackBlitz(Editor): https://stackblitz.com/edit/ngx-face-api-js-demo-webcam

---

**App Screenshot**

<img width="200" src="https://user-images.githubusercontent.com/35218186/73030325-b9a9c800-3e7c-11ea-8919-2307927e3983.png">


Thanks.

**Comment by kamiazya** [comment]
@luiza-avelino 

Sorry, I read my intentions incorrectly.

The actual answer was **No**.

In the current implementation, TinyModel is not used.

**Comment by abhashpr** [comment]
Hi Kamiazya

I tried to run this app by cloning it to my pc but everytime I am running into issues. 

D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam>ng serve
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber.project (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\src\workspace\workspace.js:215:42)
    at MergeMapSubscriber._tryNext (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MapSubscriber._next (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (D:\Abhash\OLD\angular\ngx-face-api-js-demo-webcam\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:86:26)

My ng version:
Angular CLI: 7.0.7
Node: 12.16.3
OS: win32 x64
Angular: 7.2.14
... common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.1001.7
@angular-devkit/build-optimizer   0.1001.7
@angular-devkit/build-webpack     0.1001.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cdk                      7.3.7
@angular/cli                      7.0.7
@angular/compiler-cli             10.1.6
@angular/language-service         7.0.4
@ngtools/webpack                  10.1.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.5.1
typescript                        3.1.6
webpack                           4.44.1


Can you please help to solve this.
